source("1_get_canadian_rent_data.R")
source("2_prepare_canadian_rent_data.R")
source("3_create_canadian_rent_model_data.R")
source("4_model_canadian_rent_data.R")
source("5_select_canadian_rent_forecast_model.R")